### PR TITLE
fix: switch verification to use verifyKey endpoint without name

### LINKED ISSUE #57: Auth Change
We should use `verifyKey` instead of `verify`.

### PR DESCRIPTION
**Pull request by dkonieczek**

### CODE REVIEW

**Review by korgon — APPROVED** [review]

File: src/services/ConfigApi.js [hunk 1]
```diff
@@ -16,8 +16,8 @@ export class ConfigApi {
 		}
 	}
 
-	async validateSite(name, siteId) {
-		const apiPath = `${this.host}/api/customer/${siteId}/verify`;
+	async validateSite(siteId) {
+		const apiPath = `${this.host}/api/customer/${siteId}/verifyKey`;
 
 		const response = await fetch(apiPath, {
 			method: 'post',
```
Comment (korgon) [inline src/services/ConfigApi.js]: I believe it is no longer a `post` request.

https://github.com/searchspring/smc-config-api

**Review by korgon — CHANGES_REQUESTED** [review]

**Review by korgon — APPROVED** [review]
